//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ShopID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ShopName { get; set; }
        public string ShopUrl { get; set; }
    }
}
